<a href="https://cognitiveclass.ai/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork20718188-2022-01-01"><img src = "https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width = 400> </a>

<h1 align=center><font size = 5>Regression Models with Keras</font></h1>

## Introduction

As we discussed in the videos, despite the popularity of more powerful libraries such as PyToch and TensorFlow, they are not easy to use and have a steep learning curve. So, for people who are just starting to learn deep learning, there is no better library to use other than the Keras library.

Keras is a high-level API for building deep learning models. It has gained favor for its ease of use and syntactic simplicity facilitating fast development. As you will see in this lab and the other labs in this course, building a very complex deep learning network can be achieved with Keras with only few lines of code. You will appreciate Keras even more, once you learn how to build deep models using PyTorch and TensorFlow in the other courses.

So, in this lab, you will learn how to use the Keras library to build a regression model.

<h2>Regression Models with Keras</h2>

<h3>Objective for this Notebook<h3>    
<h5> 1. How to use the Keras library to build a regression model.</h5>
<h5> 2. Download and Clean dataset </h5>
<h5> 3. Build a Neural Network </h5>
<h5> 4. Train and Test the Network. </h5>

## Table of Contents

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>

1.  <a href="https://#item31">Download and Clean Dataset</a>
2.  <a href="https://#item32">Import Keras</a>
3.  <a href="https://#item33">Build a Neural Network</a>
4.  <a href="https://#item34">Train and Test the Network</a>

</font>
</div>

<a id="item31"></a>

## Download and Clean Dataset

Let's start by importing the <em>pandas</em> and the Numpy libraries.

In [1]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented. 
# If you run this notebook on a different environment, e.g. your desktop, you may need to uncomment and install certain libraries.

#!pip install numpy==1.21.4
#!pip install pandas==1.3.4
#!pip install keras==2.1.6

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/sklearn/utils/validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'

We will be playing around with the same dataset that we used in the videos.

<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

<strong>1. Cement</strong>

<strong>2. Blast Furnace Slag</strong>

<strong>3. Fly Ash</strong>

<strong>4. Water</strong>

<strong>5. Superplasticizer</strong>

<strong>6. Coarse Aggregate</strong>

<strong>7. Fine Aggregate</strong>

Let's download the data and read it into a <em>pandas</em> dataframe.

In [3]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

So the first concrete sample has 540 cubic meter of cement, 0 cubic meter of blast furnace slag, 0 cubic meter of fly ash, 162 cubic meter of water, 2.5 cubic meter of superplaticizer, 1040 cubic meter of coarse aggregate, 676 cubic meter of fine aggregate. Such a concrete mix which is 28 days old, has a compressive strength of 79.99 MPa.

#### Let's check how many data points we have.

In [4]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

Let's check the dataset for any missing values.

In [5]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

The data looks very clean and is ready to be used to build our model.

#### Split data into predictors and target

The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

In [7]:
concrete_data_columns = concrete_data.columns
print(concrete_data_columns)

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

Index(['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age', 'Strength'],
      dtype='object')

<a id="item2"></a>

Let's do a quick sanity check of the predictors and the target dataframes.

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [10]:
# predictors_norm = (predictors - predictors.mean()) / predictors.std()
# predictors_norm.head()

Let's save the number of predictors to *n_cols* since we will need this number when building our network.

In [11]:
n_cols = predictors.shape[1] # number of predictors
print(n_cols)

8

<a id="item1"></a>

<a id='item32'></a>

## Import Keras

Recall from the videos that Keras normally runs on top of a low-level library such as TensorFlow. This means that to be able to use the Keras library, you will have to install TensorFlow first and when you import the Keras library, it will be explicitly displayed what backend was used to install the Keras library. In CC Labs, we used TensorFlow as the backend to install Keras, so it should clearly print that when we import Keras.

#### Let's go ahead and import the Keras library

In [12]:
import keras

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

As you can see, the TensorFlow backend was used to install the Keras library.

Let's import the rest of the packages from the Keras library that we will need to build our regressoin model.

In [13]:
from keras.models import Sequential
from keras.layers import Dense

<a id='item33'></a>

## Build a Neural Network

Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

In [14]:
xtrain,xtest, ytrain, ytest=train_test_split(predictors, target,test_size=0.3, random_state=42)

In [15]:
xtest.shape

(309, 8)

In [19]:
# define regression model

def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    # compile model
    model.compile(optimizer='adam', loss="mean_squared_error")
    return model

The above function create a model that has 1 hidden layers of 10 hidden units.

<a id="item4"></a>

<a id='item34'></a>

## Train and Test the Network

Let's call the function now to create our model.

In [20]:
# build the model
model= regression_model()

Next, we will train and test the model at the same time using the *fit* method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

In [ ]:
# fit the model
mse=[]
for i in range(50):
    model.fit(xtrain, ytrain, epochs=50, verbose=2)
    pred=model.predict(xtest)
    mse.append(mean_squared_error(ytest, pred))

Epoch 1/50
 - 0s - loss: 51.7135
Epoch 2/50
 - 0s - loss: 48.5778
Epoch 3/50
 - 0s - loss: 48.9151
Epoch 4/50
 - 0s - loss: 47.6647
Epoch 5/50
 - 0s - loss: 47.5770
Epoch 6/50
 - 0s - loss: 47.2221
Epoch 7/50
 - 0s - loss: 48.3354
Epoch 8/50
 - 0s - loss: 49.1225
Epoch 9/50
 - 0s - loss: 50.6826
Epoch 10/50
 - 0s - loss: 49.6258
Epoch 11/50
 - 0s - loss: 47.9943
Epoch 12/50
 - 0s - loss: 49.6753
Epoch 13/50
 - 0s - loss: 49.0137
Epoch 14/50
 - 0s - loss: 48.0116
Epoch 15/50
 - 0s - loss: 48.0588
Epoch 16/50
 - 0s - loss: 47.9425
Epoch 17/50
 - 0s - loss: 47.9715
Epoch 18/50
 - 0s - loss: 47.6793
Epoch 19/50
 - 0s - loss: 47.5571
Epoch 20/50
 - 0s - loss: 48.3739
Epoch 21/50
 - 0s - loss: 48.5496
Epoch 22/50
 - 0s - loss: 48.2214
Epoch 23/50
 - 0s - loss: 49.5642
Epoch 24/50
 - 0s - loss: 48.0058
Epoch 25/50
 - 0s - loss: 47.9944
Epoch 26/50
 - 0s - loss: 48.0301
Epoch 27/50
 - 0s - loss: 48.3821
Epoch 28/50
 - 0s - loss: 47.7807
Epoch 29/50
 - 0s - loss: 47.5296
Epoch 30/50
 - 0s - loss: 50.1877
Epoch 31/50
 - 0s - loss: 53.3729
Epoch 32/50
 - 0s - loss: 49.5161
Epoch 33/50
 - 0s - loss: 48.8238
Epoch 34/50
 - 0s - loss: 48.4675
Epoch 35/50
 - 0s - loss: 49.1843
Epoch 36/50
 - 0s - loss: 49.5899
Epoch 37/50
 - 0s - loss: 50.5485
Epoch 38/50
 - 0s - loss: 52.4857
Epoch 39/50
 - 0s - loss: 48.6258
Epoch 40/50
 - 0s - loss: 49.3671
Epoch 41/50
 - 0s - loss: 48.0426
Epoch 42/50
 - 0s - loss: 48.2936
Epoch 43/50
 - 0s - loss: 48.0070
Epoch 44/50
 - 0s - loss: 47.5572
Epoch 45/50
 - 0s - loss: 48.5590
Epoch 46/50
 - 0s - loss: 50.0556
Epoch 47/50
 - 0s - loss: 50.7065
Epoch 48/50
 - 0s - loss: 48.6117
Epoch 49/50
 - 0s - loss: 48.7915
Epoch 50/50
 - 0s - loss: 48.1177
Epoch 1/50
 - 0s - loss: 47.6232
Epoch 2/50
 - 0s - loss: 48.5673
Epoch 3/50
 - 0s - loss: 47.8372
Epoch 4/50
 - 0s - loss: 48.7384
Epoch 5/50
 - 0s - loss: 49.1861
Epoch 6/50
 - 0s - loss: 47.9947
Epoch 7/50
 - 0s - loss: 49.8469
Epoch 8/50
 - 0s - loss: 50.9044
Epoch 9/50
 - 0s - loss: 49.1240
Epoch 10/50
 - 0s - loss: 50.3041
Epoch 11/50
 - 0s - loss: 49.6892
Epoch 12/50
 - 0s - loss: 47.8936
Epoch 13/50
 - 0s - loss: 48.1161
Epoch 14/50
 - 0s - loss: 49.1487
Epoch 15/50
 - 0s - loss: 47.8752
Epoch 16/50
 - 0s - loss: 49.5983
Epoch 17/50
 - 0s - loss: 48.5677
Epoch 18/50
 - 0s - loss: 49.5275
Epoch 19/50
 - 0s - loss: 47.8039
Epoch 20/50
 - 0s - loss: 48.3927
Epoch 21/50
 - 0s - loss: 48.2512
Epoch 22/50
 - 0s - loss: 48.1379
Epoch 23/50
 - 0s - loss: 50.0661
Epoch 24/50
 - 0s - loss: 47.3150
Epoch 25/50
 - 0s - loss: 50.2498
Epoch 26/50
 - 0s - loss: 51.0310
Epoch 27/50
 - 0s - loss: 49.5173
Epoch 28/50
 - 0s - loss: 48.3783
Epoch 29/50
 - 0s - loss: 47.8959
Epoch 30/50
 - 0s - loss: 47.9368
Epoch 31/50
 - 0s - loss: 47.8448
Epoch 32/50
 - 0s - loss: 47.7901
Epoch 33/50
 - 0s - loss: 48.1030
Epoch 34/50
 - 0s - loss: 49.9423
Epoch 35/50
 - 0s - loss: 48.1919
Epoch 36/50
 - 0s - loss: 48.2876
Epoch 37/50
 - 0s - loss: 49.6607
Epoch 38/50
 - 0s - loss: 48.9277
Epoch 39/50
 - 0s - loss: 49.4552
Epoch 40/50
 - 0s - loss: 48.9009
Epoch 41/50
 - 0s - loss: 49.7141
Epoch 42/50
 - 0s - loss: 51.4843
Epoch 43/50
 - 0s - loss: 50.7182
Epoch 44/50
 - 0s - loss: 47.7038
Epoch 45/50
 - 0s - loss: 48.1917
Epoch 46/50
 - 0s - loss: 47.7715
Epoch 47/50
 - 0s - loss: 47.9280
Epoch 48/50
 - 0s - loss: 47.3431
Epoch 49/50
 - 0s - loss: 47.8022
Epoch 50/50
 - 0s - loss: 47.7437
Epoch 1/50
 - 0s - loss: 48.2423
Epoch 2/50
 - 0s - loss: 48.1890
Epoch 3/50
 - 0s - loss: 49.3197
Epoch 4/50
 - 0s - loss: 49.1134
Epoch 5/50
 - 0s - loss: 48.3145
Epoch 6/50
 - 0s - loss: 47.5553
Epoch 7/50
 - 0s - loss: 48.1539
Epoch 8/50
 - 0s - loss: 48.3860
Epoch 9/50
 - 0s - loss: 48.7109
Epoch 10/50
 - 0s - loss: 47.8255
Epoch 11/50
 - 0s - loss: 50.6292
Epoch 12/50
 - 0s - loss: 48.5191
Epoch 13/50
 - 0s - loss: 47.7231
Epoch 14/50
 - 0s - loss: 49.4480
Epoch 15/50
 - 0s - loss: 49.6680
Epoch 16/50
 - 0s - loss: 48.2931
Epoch 17/50
 - 0s - loss: 48.7737
Epoch 18/50
 - 0s - loss: 47.8995
Epoch 19/50
 - 0s - loss: 48.6479
Epoch 20/50
 - 0s - loss: 47.7819
Epoch 21/50
 - 0s - loss: 49.3897
Epoch 22/50
 - 0s - loss: 48.8553
Epoch 23/50
 - 0s - loss: 49.3650
Epoch 24/50
 - 0s - loss: 48.7245
Epoch 25/50
 - 0s - loss: 48.1926
Epoch 26/50
 - 0s - loss: 49.4868
Epoch 27/50
 - 0s - loss: 48.2477
Epoch 28/50
 - 0s - loss: 48.7667
Epoch 29/50
 - 0s - loss: 48.0816
Epoch 30/50
 - 0s - loss: 48.0542
Epoch 31/50
 - 0s - loss: 48.0320
Epoch 32/50
 - 0s - loss: 47.9929
Epoch 33/50
 - 0s - loss: 49.1441
Epoch 34/50
 - 0s - loss: 48.6089
Epoch 35/50
 - 0s - loss: 48.8849
Epoch 36/50
 - 0s - loss: 50.4216
Epoch 37/50
 - 0s - loss: 48.1485
Epoch 38/50
 - 0s - loss: 47.8549
Epoch 39/50
 - 0s - loss: 49.6221
Epoch 40/50
 - 0s - loss: 48.3596
Epoch 41/50
 - 0s - loss: 48.1389
Epoch 42/50
 - 0s - loss: 49.8953
Epoch 43/50
 - 0s - loss: 48.3243
Epoch 44/50
 - 0s - loss: 48.2632
Epoch 45/50
 - 0s - loss: 47.8731
Epoch 46/50
 - 0s - loss: 47.8150
Epoch 47/50
 - 0s - loss: 48.5564
Epoch 48/50
 - 0s - loss: 48.0855
Epoch 49/50
 - 0s - loss: 53.3381
Epoch 50/50
 - 0s - loss: 51.6174
Epoch 1/50
 - 0s - loss: 47.9593
Epoch 2/50
 - 0s - loss: 47.9799
Epoch 3/50
 - 0s - loss: 48.4092
Epoch 4/50
 - 0s - loss: 49.9768
Epoch 5/50
 - 0s - loss: 49.7778
Epoch 6/50
 - 0s - loss: 50.3378
Epoch 7/50
 - 0s - loss: 50.5213
Epoch 8/50
 - 0s - loss: 48.2099
Epoch 9/50
 - 0s - loss: 49.7157
Epoch 10/50
 - 0s - loss: 48.6238
Epoch 11/50
 - 0s - loss: 48.4371
Epoch 12/50
 - 0s - loss: 47.9028
Epoch 13/50
 - 0s - loss: 48.2140
Epoch 14/50
 - 0s - loss: 48.7743
Epoch 15/50
 - 0s - loss: 48.3566
Epoch 16/50
 - 0s - loss: 48.2751
Epoch 17/50
 - 0s - loss: 48.3751
Epoch 18/50
 - 0s - loss: 47.6162
Epoch 19/50
 - 0s - loss: 48.0389
Epoch 20/50
 - 0s - loss: 49.9083
Epoch 21/50
 - 0s - loss: 48.3458
Epoch 22/50
 - 0s - loss: 49.0951
Epoch 23/50
 - 0s - loss: 47.5115
Epoch 24/50
 - 0s - loss: 47.5064
Epoch 25/50
 - 0s - loss: 49.1390
Epoch 26/50
 - 0s - loss: 48.9141
Epoch 27/50
 - 0s - loss: 48.1464
Epoch 28/50
 - 0s - loss: 48.7026
Epoch 29/50
 - 0s - loss: 47.7837
Epoch 30/50
 - 0s - loss: 48.5972
Epoch 31/50
 - 0s - loss: 48.6559
Epoch 32/50
 - 0s - loss: 49.6275
Epoch 33/50
 - 0s - loss: 50.7098
Epoch 34/50
 - 0s - loss: 47.8404
Epoch 35/50
 - 0s - loss: 48.0526
Epoch 36/50
 - 0s - loss: 48.7425
Epoch 37/50
 - 0s - loss: 47.5638
Epoch 38/50
 - 0s - loss: 49.1372
Epoch 39/50
 - 0s - loss: 47.8675
Epoch 40/50
 - 0s - loss: 47.6330
Epoch 41/50
 - 0s - loss: 51.7176
Epoch 42/50
 - 0s - loss: 48.3951
Epoch 43/50
 - 0s - loss: 48.9687
Epoch 44/50
 - 0s - loss: 47.9123
Epoch 45/50
 - 0s - loss: 47.6897
Epoch 46/50
 - 0s - loss: 49.3722
Epoch 47/50
 - 0s - loss: 47.8247
Epoch 48/50
 - 0s - loss: 47.7095
Epoch 49/50
 - 0s - loss: 48.5328
Epoch 50/50
 - 0s - loss: 48.3973
Epoch 1/50
 - 0s - loss: 50.0704
Epoch 2/50
 - 0s - loss: 48.2117
Epoch 3/50
 - 0s - loss: 49.2436
Epoch 4/50
 - 0s - loss: 48.3715
Epoch 5/50
 - 0s - loss: 47.6537
Epoch 6/50
 - 0s - loss: 47.9368
Epoch 7/50
 - 0s - loss: 49.4139
Epoch 8/50
 - 0s - loss: 47.6914
Epoch 9/50
 - 0s - loss: 48.3537
Epoch 10/50
 - 0s - loss: 47.8925
Epoch 11/50
 - 0s - loss: 49.5909
Epoch 12/50
 - 0s - loss: 47.7518
Epoch 13/50
 - 0s - loss: 47.6209
Epoch 14/50
 - 0s - loss: 47.7603
Epoch 15/50
 - 0s - loss: 47.9131
Epoch 16/50
 - 0s - loss: 47.9390
Epoch 17/50
 - 0s - loss: 47.7143
Epoch 18/50
 - 0s - loss: 48.2670
Epoch 19/50
 - 0s - loss: 50.0755
Epoch 20/50
 - 0s - loss: 49.3052
Epoch 21/50
 - 0s - loss: 49.0957
Epoch 22/50
 - 0s - loss: 48.3539
Epoch 23/50
 - 0s - loss: 48.3756
Epoch 24/50
 - 0s - loss: 48.4645
Epoch 25/50
 - 0s - loss: 49.7726
Epoch 26/50
 - 0s - loss: 47.6332
Epoch 27/50
 - 0s - loss: 47.9973
Epoch 28/50
 - 0s - loss: 47.7143
Epoch 29/50
 - 0s - loss: 48.4311
Epoch 30/50
 - 0s - loss: 50.1552
Epoch 31/50
 - 0s - loss: 49.2829
Epoch 32/50
 - 0s - loss: 47.5472
Epoch 33/50
 - 0s - loss: 47.5919
Epoch 34/50
 - 0s - loss: 47.7170
Epoch 35/50
 - 0s - loss: 47.7256
Epoch 36/50
 - 0s - loss: 51.2573
Epoch 37/50
 - 0s - loss: 49.1343
Epoch 38/50
 - 0s - loss: 48.1858
Epoch 39/50
 - 0s - loss: 48.0082
Epoch 40/50
 - 0s - loss: 49.9587
Epoch 41/50
 - 0s - loss: 48.4892
Epoch 42/50
 - 0s - loss: 48.5831
Epoch 43/50
 - 0s - loss: 49.8777
Epoch 44/50
 - 0s - loss: 51.5269
Epoch 45/50
 - 0s - loss: 50.1302
Epoch 46/50
 - 0s - loss: 48.2480
Epoch 47/50
 - 0s - loss: 48.2695
Epoch 48/50
 - 0s - loss: 48.3243
Epoch 49/50
 - 0s - loss: 49.6179
Epoch 50/50
 - 0s - loss: 48.5147
Epoch 1/50
 - 0s - loss: 48.5597
Epoch 2/50
 - 0s - loss: 47.6877
Epoch 3/50
 - 0s - loss: 47.9834
Epoch 4/50
 - 0s - loss: 47.9460
Epoch 5/50
 - 0s - loss: 47.6997
Epoch 6/50
 - 0s - loss: 48.1908
Epoch 7/50
 - 0s - loss: 47.5763
Epoch 8/50
 - 0s - loss: 48.5142
Epoch 9/50
 - 0s - loss: 49.2114
Epoch 10/50
 - 0s - loss: 48.3582
Epoch 11/50
 - 0s - loss: 48.1581
Epoch 12/50
 - 0s - loss: 48.7984
Epoch 13/50
 - 0s - loss: 49.1729
Epoch 14/50
 - 0s - loss: 48.9132
Epoch 15/50
 - 0s - loss: 48.6413
Epoch 16/50
 - 0s - loss: 49.4648
Epoch 17/50
 - 0s - loss: 48.0928
Epoch 18/50
 - 0s - loss: 48.9054
Epoch 19/50
 - 0s - loss: 48.4164
Epoch 20/50
 - 0s - loss: 48.2884
Epoch 21/50
 - 0s - loss: 49.2857
Epoch 22/50
 - 0s - loss: 50.4765
Epoch 23/50
 - 0s - loss: 48.1496
Epoch 24/50
 - 0s - loss: 47.7255
Epoch 25/50
 - 0s - loss: 48.4528
Epoch 26/50
 - 0s - loss: 47.6647
Epoch 27/50
 - 0s - loss: 47.3907
Epoch 28/50
 - 0s - loss: 47.7214
Epoch 29/50
 - 0s - loss: 47.9232
Epoch 30/50
 - 0s - loss: 47.6518
Epoch 31/50
 - 0s - loss: 51.2051
Epoch 32/50
 - 0s - loss: 48.1377
Epoch 33/50
 - 0s - loss: 48.2713
Epoch 34/50
 - 0s - loss: 47.6743
Epoch 35/50
 - 0s - loss: 47.5708
Epoch 36/50
 - 0s - loss: 48.5807
Epoch 37/50
 - 0s - loss: 48.1551
Epoch 38/50
 - 0s - loss: 51.4146
Epoch 39/50
 - 0s - loss: 48.6610
Epoch 40/50
 - 0s - loss: 47.6242
Epoch 41/50
 - 0s - loss: 48.2715
Epoch 42/50
 - 0s - loss: 49.9179
Epoch 43/50
 - 0s - loss: 51.1104
Epoch 44/50
 - 0s - loss: 47.9152
Epoch 45/50
 - 0s - loss: 50.3332
Epoch 46/50
 - 0s - loss: 49.3145
Epoch 47/50
 - 0s - loss: 48.1667
Epoch 48/50
 - 0s - loss: 48.3079
Epoch 49/50
 - 0s - loss: 48.4810
Epoch 50/50
 - 0s - loss: 50.0342
Epoch 1/50
 - 0s - loss: 47.4472
Epoch 2/50
 - 0s - loss: 49.5558
Epoch 3/50
 - 0s - loss: 49.3970
Epoch 4/50
 - 0s - loss: 48.4611
Epoch 5/50
 - 0s - loss: 47.7130
Epoch 6/50
 - 0s - loss: 48.6164
Epoch 7/50
 - 0s - loss: 49.3496
Epoch 8/50
 - 0s - loss: 48.1279
Epoch 9/50
 - 0s - loss: 48.2120
Epoch 10/50
 - 0s - loss: 48.0702
Epoch 11/50
 - 0s - loss: 47.8772
Epoch 12/50
 - 0s - loss: 47.5022
Epoch 13/50
 - 0s - loss: 48.8288
Epoch 14/50
 - 0s - loss: 47.5258
Epoch 15/50
 - 0s - loss: 47.7799
Epoch 16/50
 - 0s - loss: 48.7725
Epoch 17/50
 - 0s - loss: 50.3202
Epoch 18/50
 - 0s - loss: 48.1655
Epoch 19/50
 - 0s - loss: 48.6001
Epoch 20/50
 - 0s - loss: 48.3101
Epoch 21/50
 - 0s - loss: 47.9375
Epoch 22/50
 - 0s - loss: 47.6739
Epoch 23/50
 - 0s - loss: 48.8309
Epoch 24/50
 - 0s - loss: 48.9538
Epoch 25/50
 - 0s - loss: 49.4888
Epoch 26/50
 - 0s - loss: 50.5612
Epoch 27/50
 - 0s - loss: 49.7487
Epoch 28/50
 - 0s - loss: 48.2357
Epoch 29/50
 - 0s - loss: 47.9781
Epoch 30/50
 - 0s - loss: 48.8895
Epoch 31/50
 - 0s - loss: 50.7593
Epoch 32/50
 - 0s - loss: 49.2948
Epoch 33/50
 - 0s - loss: 48.9198
Epoch 34/50
 - 0s - loss: 48.6955
Epoch 35/50
 - 0s - loss: 47.5616
Epoch 36/50
 - 0s - loss: 47.5461
Epoch 37/50
 - 0s - loss: 48.0156
Epoch 38/50
 - 0s - loss: 49.2517
Epoch 39/50
 - 0s - loss: 48.2405
Epoch 40/50
 - 0s - loss: 48.8517
Epoch 41/50
 - 0s - loss: 48.4533
Epoch 42/50
 - 0s - loss: 48.4151
Epoch 43/50
 - 0s - loss: 47.7337
Epoch 44/50
 - 0s - loss: 48.5354
Epoch 45/50
 - 0s - loss: 48.5021
Epoch 46/50
 - 0s - loss: 47.7170
Epoch 47/50
 - 0s - loss: 48.0041
Epoch 48/50
 - 0s - loss: 48.1548
Epoch 49/50
 - 0s - loss: 50.4770
Epoch 50/50
 - 0s - loss: 49.4083
Epoch 1/50
 - 0s - loss: 47.7824
Epoch 2/50
 - 0s - loss: 47.6885
Epoch 3/50
 - 0s - loss: 48.2831
Epoch 4/50
 - 0s - loss: 47.5673
Epoch 5/50
 - 0s - loss: 48.2784
Epoch 6/50
 - 0s - loss: 48.5881
Epoch 7/50
 - 0s - loss: 49.8865
Epoch 8/50
 - 0s - loss: 48.2544
Epoch 9/50
 - 0s - loss: 47.8693
Epoch 10/50
 - 0s - loss: 48.2941
Epoch 11/50
 - 0s - loss: 48.0569
Epoch 12/50
 - 0s - loss: 48.6939
Epoch 13/50
 - 0s - loss: 48.5075
Epoch 14/50
 - 0s - loss: 48.3703
Epoch 15/50
 - 0s - loss: 47.7255
Epoch 16/50
 - 0s - loss: 49.4869
Epoch 17/50
 - 0s - loss: 48.3504
Epoch 18/50
 - 0s - loss: 47.7007
Epoch 19/50
 - 0s - loss: 48.0933
Epoch 20/50
 - 0s - loss: 48.6929
Epoch 21/50
 - 0s - loss: 48.1025
Epoch 22/50
 - 0s - loss: 49.7890
Epoch 23/50
 - 0s - loss: 48.7846
Epoch 24/50
 - 0s - loss: 47.8416
Epoch 25/50
 - 0s - loss: 49.2705
Epoch 26/50
 - 0s - loss: 49.4287
Epoch 27/50
 - 0s - loss: 47.9384
Epoch 28/50
 - 0s - loss: 47.7354
Epoch 29/50
 - 0s - loss: 49.4746
Epoch 30/50
 - 0s - loss: 47.7329
Epoch 31/50
 - 0s - loss: 48.9922
Epoch 32/50
 - 0s - loss: 47.7503
Epoch 33/50
 - 0s - loss: 47.6563
Epoch 34/50
 - 0s - loss: 47.8645
Epoch 35/50
 - 0s - loss: 47.9998
Epoch 36/50
 - 0s - loss: 47.6968
Epoch 37/50
 - 0s - loss: 48.0577
Epoch 38/50
 - 0s - loss: 48.6053
Epoch 39/50
 - 0s - loss: 49.1100
Epoch 40/50
 - 0s - loss: 48.7492
Epoch 41/50
 - 0s - loss: 47.9387
Epoch 42/50
 - 0s - loss: 48.9643
Epoch 43/50
 - 0s - loss: 48.2891
Epoch 44/50
 - 0s - loss: 47.5247
Epoch 45/50
 - 0s - loss: 47.8968
Epoch 46/50
 - 0s - loss: 48.3739
Epoch 47/50
 - 0s - loss: 47.9192
Epoch 48/50
 - 0s - loss: 47.9572
Epoch 49/50
 - 0s - loss: 47.8823
Epoch 50/50
 - 0s - loss: 48.9587
Epoch 1/50
 - 0s - loss: 50.2677
Epoch 2/50
 - 0s - loss: 49.0773
Epoch 3/50
 - 0s - loss: 49.2515
Epoch 4/50
 - 0s - loss: 48.9575
Epoch 5/50
 - 0s - loss: 50.0360
Epoch 6/50
 - 0s - loss: 52.6706
Epoch 7/50
 - 0s - loss: 48.5455
Epoch 8/50
 - 0s - loss: 47.6568
Epoch 9/50
 - 0s - loss: 47.8577
Epoch 10/50
 - 0s - loss: 50.0289
Epoch 11/50
 - 0s - loss: 49.4827
Epoch 12/50
 - 0s - loss: 48.0207
Epoch 13/50
 - 0s - loss: 47.7932
Epoch 14/50
 - 0s - loss: 47.5576
Epoch 15/50
 - 0s - loss: 49.6172
Epoch 16/50
 - 0s - loss: 48.9670
Epoch 17/50
 - 0s - loss: 47.9187
Epoch 18/50
 - 0s - loss: 47.9276
Epoch 19/50
 - 0s - loss: 48.5072
Epoch 20/50
 - 0s - loss: 47.8256
Epoch 21/50
 - 0s - loss: 48.5174
Epoch 22/50
 - 0s - loss: 47.9049
Epoch 23/50
 - 0s - loss: 49.9395
Epoch 24/50
 - 0s - loss: 48.4229
Epoch 25/50
 - 0s - loss: 47.9575
Epoch 26/50
 - 0s - loss: 48.5683
Epoch 27/50
 - 0s - loss: 47.7517
Epoch 28/50
 - 0s - loss: 48.5105
Epoch 29/50
 - 0s - loss: 47.5081
Epoch 30/50
 - 0s - loss: 48.1504
Epoch 31/50
 - 0s - loss: 48.1653
Epoch 32/50
 - 0s - loss: 48.8332
Epoch 33/50
 - 0s - loss: 48.0773
Epoch 34/50
 - 0s - loss: 47.8793
Epoch 35/50
 - 0s - loss: 49.2296
Epoch 36/50
 - 0s - loss: 47.4351
Epoch 37/50
 - 0s - loss: 47.8312
Epoch 38/50
 - 0s - loss: 48.6738
Epoch 39/50
 - 0s - loss: 48.9407
Epoch 40/50
 - 0s - loss: 48.0850
Epoch 41/50
 - 0s - loss: 48.0375
Epoch 42/50
 - 0s - loss: 47.6527
Epoch 43/50
 - 0s - loss: 48.9423
Epoch 44/50
 - 0s - loss: 51.2662
Epoch 45/50
 - 0s - loss: 49.0870
Epoch 46/50
 - 0s - loss: 47.8531
Epoch 47/50
 - 0s - loss: 48.4314
Epoch 48/50
 - 0s - loss: 47.9729
Epoch 49/50
 - 0s - loss: 49.8903
Epoch 50/50
 - 0s - loss: 48.5179
Epoch 1/50
 - 0s - loss: 48.7147
Epoch 2/50
 - 0s - loss: 47.9693
Epoch 3/50
 - 0s - loss: 47.8423
Epoch 4/50
 - 0s - loss: 47.9767
Epoch 5/50
 - 0s - loss: 47.3238
Epoch 6/50
 - 0s - loss: 48.2761
Epoch 7/50
 - 0s - loss: 48.0996
Epoch 8/50
 - 0s - loss: 48.6138
Epoch 9/50
 - 0s - loss: 47.9268
Epoch 10/50
 - 0s - loss: 47.8872
Epoch 11/50
 - 0s - loss: 47.4908
Epoch 12/50
 - 0s - loss: 49.1920
Epoch 13/50
 - 0s - loss: 47.6122
Epoch 14/50
 - 0s - loss: 47.6953
Epoch 15/50
 - 0s - loss: 48.6105
Epoch 16/50
 - 0s - loss: 47.9446
Epoch 17/50
 - 0s - loss: 48.3932
Epoch 18/50
 - 0s - loss: 48.3828
Epoch 19/50
 - 0s - loss: 48.9429
Epoch 20/50
 - 0s - loss: 49.5640
Epoch 21/50
 - 0s - loss: 48.4843
Epoch 22/50
 - 0s - loss: 47.8133
Epoch 23/50
 - 0s - loss: 49.8127
Epoch 24/50
 - 0s - loss: 47.7164
Epoch 25/50
 - 0s - loss: 48.3790
Epoch 26/50
 - 0s - loss: 48.5780
Epoch 27/50
 - 0s - loss: 49.0452
Epoch 28/50
 - 0s - loss: 47.3920
Epoch 29/50
 - 0s - loss: 47.9545
Epoch 30/50
 - 0s - loss: 49.0510
Epoch 31/50
 - 0s - loss: 49.0782
Epoch 32/50
 - 0s - loss: 47.7526
Epoch 33/50
 - 0s - loss: 47.4974
Epoch 34/50
 - 0s - loss: 47.6607
Epoch 35/50
 - 0s - loss: 48.2935
Epoch 36/50
 - 0s - loss: 48.1700
Epoch 37/50
 - 0s - loss: 47.8434
Epoch 38/50
 - 0s - loss: 48.2975
Epoch 39/50
 - 0s - loss: 47.6860
Epoch 40/50
 - 0s - loss: 49.8044
Epoch 41/50
 - 0s - loss: 48.4076
Epoch 42/50
 - 0s - loss: 48.2781
Epoch 43/50
 - 0s - loss: 47.5589
Epoch 44/50
 - 0s - loss: 48.1382
Epoch 45/50
 - 0s - loss: 50.1482
Epoch 46/50
 - 0s - loss: 47.8145
Epoch 47/50
 - 0s - loss: 48.9510
Epoch 48/50
 - 0s - loss: 47.9865
Epoch 49/50
 - 0s - loss: 47.6553
Epoch 50/50
 - 0s - loss: 48.1735
Epoch 1/50
 - 0s - loss: 47.8352
Epoch 2/50
 - 0s - loss: 47.9066
Epoch 3/50
 - 0s - loss: 48.0864
Epoch 4/50
 - 0s - loss: 47.8944
Epoch 5/50
 - 0s - loss: 47.6470
Epoch 6/50
 - 0s - loss: 49.2924
Epoch 7/50
 - 0s - loss: 47.4988
Epoch 8/50
 - 0s - loss: 48.6169
Epoch 9/50
 - 0s - loss: 50.3082
Epoch 10/50
 - 0s - loss: 48.7351
Epoch 11/50
 - 0s - loss: 49.1756
Epoch 12/50
 - 0s - loss: 47.8292
Epoch 13/50
 - 0s - loss: 48.3004
Epoch 14/50
 - 0s - loss: 48.4474
Epoch 15/50
 - 0s - loss: 48.9571
Epoch 16/50
 - 0s - loss: 47.5704
Epoch 17/50
 - 0s - loss: 49.2076
Epoch 18/50
 - 0s - loss: 49.3130
Epoch 19/50
 - 0s - loss: 49.8573
Epoch 20/50
 - 0s - loss: 48.2440
Epoch 21/50
 - 0s - loss: 47.4859
Epoch 22/50
 - 0s - loss: 48.2110
Epoch 23/50
 - 0s - loss: 48.0050
Epoch 24/50
 - 0s - loss: 47.4689
Epoch 25/50
 - 0s - loss: 47.8421
Epoch 26/50
 - 0s - loss: 48.1392
Epoch 27/50
 - 0s - loss: 47.6062
Epoch 28/50
 - 0s - loss: 48.4728
Epoch 29/50
 - 0s - loss: 47.4074
Epoch 30/50
 - 0s - loss: 48.2422
Epoch 31/50
 - 0s - loss: 47.6299
Epoch 32/50
 - 0s - loss: 48.9168
Epoch 33/50
 - 0s - loss: 50.0361
Epoch 34/50
 - 0s - loss: 47.7457
Epoch 35/50
 - 0s - loss: 49.3089
Epoch 36/50
 - 0s - loss: 48.6747
Epoch 37/50
 - 0s - loss: 47.7278
Epoch 38/50
 - 0s - loss: 49.0606
Epoch 39/50
 - 0s - loss: 50.6187
Epoch 40/50
 - 0s - loss: 47.9817
Epoch 41/50
 - 0s - loss: 47.8192
Epoch 42/50
 - 0s - loss: 47.5825
Epoch 43/50
 - 0s - loss: 48.9588
Epoch 44/50
 - 0s - loss: 48.0510
Epoch 45/50
 - 0s - loss: 48.9273
Epoch 46/50
 - 0s - loss: 47.7952
Epoch 47/50
 - 0s - loss: 48.7456
Epoch 48/50
 - 0s - loss: 48.0134
Epoch 49/50
 - 0s - loss: 47.7389
Epoch 50/50
 - 0s - loss: 49.3795
Epoch 1/50
 - 0s - loss: 49.9272
Epoch 2/50
 - 0s - loss: 50.0009
Epoch 3/50
 - 0s - loss: 48.2464
Epoch 4/50
 - 0s - loss: 48.8634
Epoch 5/50
 - 0s - loss: 49.8939
Epoch 6/50
 - 0s - loss: 49.1794
Epoch 7/50
 - 0s - loss: 49.9829
Epoch 8/50
 - 0s - loss: 48.0960
Epoch 9/50
 - 0s - loss: 48.6210
Epoch 10/50
 - 0s - loss: 48.0689
Epoch 11/50
 - 0s - loss: 49.4788
Epoch 12/50
 - 0s - loss: 47.8270
Epoch 13/50
 - 0s - loss: 50.6069
Epoch 14/50
 - 0s - loss: 48.0123
Epoch 15/50
 - 0s - loss: 53.3254
Epoch 16/50
 - 0s - loss: 49.5222
Epoch 17/50
 - 0s - loss: 47.3260
Epoch 18/50
 - 0s - loss: 49.1294
Epoch 19/50
 - 0s - loss: 48.2373
Epoch 20/50
 - 0s - loss: 47.7006
Epoch 21/50
 - 0s - loss: 48.0749
Epoch 22/50
 - 0s - loss: 47.9070
Epoch 23/50
 - 0s - loss: 47.4643
Epoch 24/50
 - 0s - loss: 48.2643
Epoch 25/50
 - 0s - loss: 47.8753
Epoch 26/50
 - 0s - loss: 47.7759
Epoch 27/50
 - 0s - loss: 47.7661
Epoch 28/50
 - 0s - loss: 48.1719
Epoch 29/50
 - 0s - loss: 48.2934
Epoch 30/50
 - 0s - loss: 47.8509
Epoch 31/50
 - 0s - loss: 47.7267
Epoch 32/50
 - 0s - loss: 47.9474
Epoch 33/50
 - 0s - loss: 47.6151
Epoch 34/50
 - 0s - loss: 49.5487
Epoch 35/50
 - 0s - loss: 47.5287
Epoch 36/50
 - 0s - loss: 48.1721
Epoch 37/50
 - 0s - loss: 48.0275
Epoch 38/50
 - 0s - loss: 50.5617
Epoch 39/50
 - 0s - loss: 49.4497
Epoch 40/50
 - 0s - loss: 49.6222
Epoch 41/50
 - 0s - loss: 48.7695
Epoch 42/50

In [26]:
mean_mse=np.mean(mse)
std_mse=np.std(mse)
print("mean mse:", mean_mse, "\nstandard deviation of mse:", std_mse)

mean mse: 76.70881396844813
standard deviation of mse: 29.365045727719075

<strong>You can refer to this [link](https://keras.io/models/sequential/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork20718188-2022-01-01) to learn about other functions that you can use for prediction or evaluation.</strong>

Feel free to vary the following and note what impact each change has on the model's performance:

1.  Increase or decreate number of neurons in hidden layers
2.  Add more hidden layers
3.  Increase number of epochs

### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork20718188-2022-01-01). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By | Change Description                                          |
| ----------------- | ------- | ---------- | ----------------------------------------------------------- |
| 2020-09-21        | 2.0     | Srishti    | Migrated Lab to Markdown and added to course repo in GitLab |

<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>

This notebook is part of a course on **Coursera** called *Introduction to Deep Learning & Neural Networks with Keras*. If you accessed this notebook outside the course, you can take this course online by clicking [here](https://cocl.us/DL0101EN_Coursera_Week3\_LAB1).

<hr>

Copyright © 2019 [IBM Developer Skills Network](https://cognitiveclass.ai/?utm_medium=dswb&utm_source=bducopyrightlink&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork20718188-2022-01-01&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0101ENSkillsNetwork20718188-2022-01-01).