In [18]:
import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [19]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [20]:
concrete_data.shape

(1030, 9)

In [21]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [22]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [23]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [24]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [30]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [31]:
n_cols = predictors.shape[1]

In [32]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [33]:
# build the model
model = regression_model()
mse_total = list()

# a loop for 50 times calculation for mse
for i in range(50):
    
    # train_test_split function to split the datasets into train and test
    predictors_train, predictors_test, target_train, target_test = train_test_split(predictors, target, test_size=0.30, random_state = 30)
    
    # fitting with 50 epochs
    model.fit(predictors_train, target_train, validation_split=0.3, epochs=50, verbose=2)
    
    prediction = model.predict(predictors_test)
    mse = mean_squared_error(prediction, target_test)
    mse_total.append(mse)

Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 3384.2419 - val_loss: 2150.2438
Epoch 2/50
 - 0s - loss: 1564.2844 - val_loss: 833.9026
Epoch 3/50
 - 0s - loss: 531.3984 - val_loss: 377.9072
Epoch 4/50
 - 0s - loss: 384.5587 - val_loss: 363.5765
Epoch 5/50
 - 0s - loss: 339.4260 - val_loss: 327.5409
Epoch 6/50
 - 0s - loss: 319.3204 - val_loss: 303.6513
Epoch 7/50
 - 0s - loss: 297.5840 - val_loss: 285.0272
Epoch 8/50
 - 0s - loss: 279.5098 - val_loss: 268.2977
Epoch 9/50
 - 0s - loss: 263.6145 - val_loss: 253.0326
Epoch 10/50
 - 0s - loss: 248.3294 - val_loss: 238.4498
Epoch 11/50
 - 0s - loss: 234.9854 - val_loss: 226.9647
Epoch 12/50
 - 0s - loss: 221.0802 - val_loss: 213.6236
Epoch 13/50
 - 0s - loss: 209.5999 - val_loss: 202.7523
Epoch 14/50
 - 0s - loss: 198.9109 - val_loss: 192.8386
Epoch 15/50
 - 0s - loss: 187.9573 - val_loss: 183.4593
Epoch 16/50
 - 0s - loss: 179.0430 - val_loss: 174.9474
Epoch 17/50
 - 0s - loss: 169.9767 - val_loss: 168.4485
Epoch 18/50
 - 0s - loss: 162.1513 - val_loss: 161.0909
Epoch 19/50
 - 0s - loss: 155.0140 - val_loss: 155.1181
Epoch 20/50
 - 0s - loss: 149.4169 - val_loss: 148.8779
Epoch 21/50
 - 0s - loss: 143.5603 - val_loss: 144.4781
Epoch 22/50
 - 0s - loss: 137.2019 - val_loss: 139.3080
Epoch 23/50
 - 0s - loss: 132.6052 - val_loss: 135.5541
Epoch 24/50
 - 0s - loss: 128.6508 - val_loss: 132.2988
Epoch 25/50
 - 0s - loss: 125.6289 - val_loss: 129.0847
Epoch 26/50
 - 0s - loss: 121.8192 - val_loss: 126.1372
Epoch 27/50
 - 0s - loss: 118.8310 - val_loss: 123.9602
Epoch 28/50
 - 0s - loss: 116.1956 - val_loss: 121.3272
Epoch 29/50
 - 0s - loss: 115.1324 - val_loss: 120.3267
Epoch 30/50
 - 0s - loss: 112.9629 - val_loss: 118.3171
Epoch 31/50
 - 0s - loss: 110.9516 - val_loss: 116.8760
Epoch 32/50
 - 0s - loss: 110.1462 - val_loss: 116.7245
Epoch 33/50
 - 0s - loss: 108.3478 - val_loss: 114.6735
Epoch 34/50
 - 0s - loss: 107.4088 - val_loss: 114.0575
Epoch 35/50
 - 0s - loss: 107.0075 - val_loss: 113.4765
Epoch 36/50
 - 0s - loss: 106.2381 - val_loss: 113.1583
Epoch 37/50
 - 0s - loss: 103.9661 - val_loss: 112.2599
Epoch 38/50
 - 0s - loss: 103.9803 - val_loss: 112.1448
Epoch 39/50
 - 0s - loss: 102.1894 - val_loss: 111.3561
Epoch 40/50
 - 0s - loss: 103.8150 - val_loss: 110.4614
Epoch 41/50
 - 0s - loss: 101.8392 - val_loss: 110.2735
Epoch 42/50
 - 0s - loss: 101.5713 - val_loss: 109.5181
Epoch 43/50
 - 0s - loss: 101.3924 - val_loss: 109.4664
Epoch 44/50
 - 0s - loss: 100.4385 - val_loss: 110.9063
Epoch 45/50
 - 0s - loss: 100.4580 - val_loss: 108.2776
Epoch 46/50
 - 0s - loss: 99.3538 - val_loss: 107.8876
Epoch 47/50
 - 0s - loss: 98.9340 - val_loss: 107.7074
Epoch 48/50
 - 0s - loss: 98.0513 - val_loss: 107.6703
Epoch 49/50
 - 0s - loss: 97.8319 - val_loss: 107.0205
Epoch 50/50
 - 0s - loss: 97.1974 - val_loss: 107.1256
Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 96.9414 - val_loss: 106.4361
Epoch 2/50
 - 0s - loss: 97.5848 - val_loss: 106.2382
Epoch 3/50
 - 0s - loss: 96.9757 - val_loss: 106.0617
Epoch 4/50
 - 0s - loss: 96.0892 - val_loss: 106.2423
Epoch 5/50
 - 0s - loss: 95.6427 - val_loss: 105.6843
Epoch 6/50
 - 0s - loss: 95.9264 - val_loss: 105.9434
Epoch 7/50
 - 0s - loss: 94.3239 - val_loss: 108.3926
Epoch 8/50
 - 0s - loss: 99.8558 - val_loss: 104.3987
Epoch 9/50
 - 0s - loss: 95.4614 - val_loss: 104.9444
Epoch 10/50
 - 0s - loss: 94.9773 - val_loss: 104.4240
Epoch 11/50
 - 0s - loss: 93.7696 - val_loss: 103.5425
Epoch 12/50
 - 0s - loss: 93.6943 - val_loss: 104.2867
Epoch 13/50
 - 0s - loss: 95.1784 - val_loss: 103.8565
Epoch 14/50
 - 0s - loss: 92.2703 - val_loss: 102.9845
Epoch 15/50
 - 0s - loss: 92.2118 - val_loss: 102.6549
Epoch 16/50
 - 0s - loss: 92.0878 - val_loss: 102.9700
Epoch 17/50
 - 0s - loss: 91.5147 - val_loss: 102.7349
Epoch 18/50
 - 0s - loss: 91.3516 - val_loss: 102.7809
Epoch 19/50
 - 0s - loss: 92.2905 - val_loss: 102.1025
Epoch 20/50
 - 0s - loss: 91.3917 - val_loss: 102.0696
Epoch 21/50
 - 0s - loss: 91.4639 - val_loss: 100.9917
Epoch 22/50
 - 0s - loss: 91.8957 - val_loss: 104.9336
Epoch 23/50
 - 0s - loss: 90.8052 - val_loss: 100.5077
Epoch 24/50
 - 0s - loss: 89.6347 - val_loss: 100.2196
Epoch 25/50
 - 0s - loss: 89.2523 - val_loss: 102.3027
Epoch 26/50
 - 0s - loss: 90.2434 - val_loss: 99.8711
Epoch 27/50
 - 0s - loss: 89.1437 - val_loss: 99.7583
Epoch 28/50
 - 0s - loss: 88.2604 - val_loss: 99.8888
Epoch 29/50
 - 0s - loss: 88.2731 - val_loss: 99.1608
Epoch 30/50
 - 0s - loss: 88.3223 - val_loss: 100.0472
Epoch 31/50
 - 0s - loss: 87.6752 - val_loss: 98.6338
Epoch 32/50
 - 0s - loss: 87.9606 - val_loss: 102.0263
Epoch 33/50
 - 0s - loss: 88.3635 - val_loss: 98.1870
Epoch 34/50
 - 0s - loss: 86.8927 - val_loss: 98.4695
Epoch 35/50
 - 0s - loss: 87.2116 - val_loss: 97.4279
Epoch 36/50
 - 0s - loss: 86.1524 - val_loss: 97.1843
Epoch 37/50
 - 0s - loss: 86.2628 - val_loss: 97.8105
Epoch 38/50
 - 0s - loss: 87.1987 - val_loss: 97.6506
Epoch 39/50
 - 0s - loss: 86.1553 - val_loss: 96.2565
Epoch 40/50
 - 0s - loss: 85.6110 - val_loss: 95.9763
Epoch 41/50
 - 0s - loss: 85.1210 - val_loss: 95.9736
Epoch 42/50
 - 0s - loss: 85.4884 - val_loss: 96.0946
Epoch 43/50
 - 0s - loss: 86.1912 - val_loss: 98.0472
Epoch 44/50
 - 0s - loss: 85.0752 - val_loss: 97.7813
Epoch 45/50
 - 0s - loss: 85.8325 - val_loss: 96.5964
Epoch 46/50
 - 0s - loss: 84.4983 - val_loss: 94.5762
Epoch 47/50
 - 0s - loss: 83.3678 - val_loss: 95.1762
Epoch 48/50
 - 0s - loss: 81.7909 - val_loss: 96.1374
Epoch 49/50
 - 0s - loss: 82.8709 - val_loss: 95.3088
Epoch 50/50
 - 0s - loss: 85.3873 - val_loss: 94.4742
Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 83.5521 - val_loss: 94.2829
Epoch 2/50
 - 0s - loss: 82.3169 - val_loss: 92.8215
Epoch 3/50
 - 0s - loss: 82.2697 - val_loss: 98.4401
Epoch 4/50
 - 0s - loss: 80.2433 - val_loss: 95.0344
Epoch 5/50
 - 0s - loss: 80.8593 - val_loss: 94.3828
Epoch 6/50
 - 0s - loss: 80.6662 - val_loss: 92.2219
Epoch 7/50
 - 0s - loss: 79.3690 - val_loss: 91.0488
Epoch 8/50
 - 0s - loss: 79.3616 - val_loss: 90.3361
Epoch 9/50
 - 0s - loss: 78.3357 - val_loss: 95.6766
Epoch 10/50
 - 0s - loss: 80.0119 - val_loss: 92.2604
Epoch 11/50
 - 0s - loss: 79.1132 - val_loss: 89.4481
Epoch 12/50
 - 0s - loss: 79.0585 - val_loss: 89.3659
Epoch 13/50
 - 0s - loss: 76.5051 - val_loss: 88.6413
Epoch 14/50
 - 0s - loss: 77.2294 - val_loss: 90.0520
Epoch 15/50
 - 0s - loss: 76.3839 - val_loss: 87.8616
Epoch 16/50
 - 0s - loss: 77.2685 - val_loss: 87.3308
Epoch 17/50
 - 0s - loss: 76.2602 - val_loss: 87.0798
Epoch 18/50
 - 0s - loss: 77.3982 - val_loss: 87.0836
Epoch 19/50
 - 0s - loss: 76.6917 - val_loss: 86.2144
Epoch 20/50
 - 0s - loss: 74.5689 - val_loss: 86.3936
Epoch 21/50
 - 0s - loss: 74.0288 - val_loss: 87.5881
Epoch 22/50
 - 0s - loss: 75.8169 - val_loss: 88.2141
Epoch 23/50
 - 0s - loss: 75.5616 - val_loss: 86.1341
Epoch 24/50
 - 0s - loss: 77.0851 - val_loss: 85.0629
Epoch 25/50
 - 0s - loss: 73.2525 - val_loss: 84.4814
Epoch 26/50
 - 0s - loss: 72.7729 - val_loss: 84.6964
Epoch 27/50
 - 0s - loss: 72.6928 - val_loss: 84.6152
Epoch 28/50
 - 0s - loss: 72.0943 - val_loss: 84.1752
Epoch 29/50
 - 0s - loss: 74.6782 - val_loss: 86.4088
Epoch 30/50
 - 0s - loss: 73.3488 - val_loss: 83.6770
Epoch 31/50
 - 0s - loss: 71.2648 - val_loss: 84.8936
Epoch 32/50
 - 0s - loss: 71.3428 - val_loss: 83.7510
Epoch 33/50
 - 0s - loss: 73.0864 - val_loss: 83.3121
Epoch 34/50
 - 0s - loss: 70.9900 - val_loss: 82.9661
Epoch 35/50
 - 0s - loss: 71.5237 - val_loss: 82.7519
Epoch 36/50
 - 0s - loss: 70.1171 - val_loss: 82.8924
Epoch 37/50
 - 0s - loss: 74.4548 - val_loss: 81.8452
Epoch 38/50
 - 0s - loss: 70.8351 - val_loss: 83.7639
Epoch 39/50
 - 0s - loss: 68.9838 - val_loss: 81.8950
Epoch 40/50
 - 0s - loss: 69.9348 - val_loss: 81.0928
Epoch 41/50
 - 0s - loss: 68.1355 - val_loss: 84.6221
Epoch 42/50
 - 0s - loss: 70.6032 - val_loss: 83.4459
Epoch 43/50
 - 0s - loss: 69.4464 - val_loss: 80.0890
Epoch 44/50
 - 0s - loss: 69.6428 - val_loss: 80.3261
Epoch 45/50
 - 0s - loss: 71.2008 - val_loss: 80.1600
Epoch 46/50
 - 0s - loss: 68.4755 - val_loss: 78.9780
Epoch 47/50
 - 0s - loss: 66.7075 - val_loss: 82.1231
Epoch 48/50
 - 0s - loss: 67.8443 - val_loss: 78.8659
Epoch 49/50
 - 0s - loss: 70.8919 - val_loss: 79.9459
Epoch 50/50
 - 0s - loss: 65.6476 - val_loss: 77.5433
Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 66.5836 - val_loss: 77.3173
Epoch 2/50
 - 0s - loss: 65.8036 - val_loss: 79.6268
Epoch 3/50
 - 0s - loss: 66.5100 - val_loss: 82.0676
Epoch 4/50
 - 0s - loss: 65.9432 - val_loss: 78.6298
Epoch 5/50
 - 0s - loss: 65.4899 - val_loss: 77.4149
Epoch 6/50
 - 0s - loss: 64.7900 - val_loss: 76.1113
Epoch 7/50
 - 0s - loss: 65.4685 - val_loss: 76.9231
Epoch 8/50
 - 0s - loss: 65.0680 - val_loss: 75.8216
Epoch 9/50
 - 0s - loss: 64.4647 - val_loss: 77.3654
Epoch 10/50
 - 0s - loss: 64.1263 - val_loss: 75.4789
Epoch 11/50
 - 0s - loss: 65.6774 - val_loss: 75.0381
Epoch 12/50
 - 0s - loss: 64.4382 - val_loss: 77.2969
Epoch 13/50
 - 0s - loss: 63.6452 - val_loss: 74.4669
Epoch 14/50
 - 0s - loss: 63.2406 - val_loss: 77.3442
Epoch 15/50
 - 0s - loss: 63.9784 - val_loss: 74.2855
Epoch 16/50
 - 0s - loss: 64.2451 - val_loss: 74.1643
Epoch 17/50
 - 0s - loss: 62.9171 - val_loss: 73.4460
Epoch 18/50
 - 0s - loss: 62.7595 - val_loss: 75.8119
Epoch 19/50
 - 0s - loss: 64.3059 - val_loss: 72.8552
Epoch 20/50
 - 0s - loss: 62.7460 - val_loss: 72.7216
Epoch 21/50
 - 0s - loss: 62.7860 - val_loss: 74.4852
Epoch 22/50
 - 0s - loss: 65.4955 - val_loss: 75.6102
Epoch 23/50
 - 0s - loss: 63.8504 - val_loss: 71.6951
Epoch 24/50
 - 0s - loss: 64.2025 - val_loss: 74.2946
Epoch 25/50
 - 0s - loss: 60.7621 - val_loss: 70.7662
Epoch 26/50
 - 0s - loss: 61.3675 - val_loss: 70.2158
Epoch 27/50
 - 0s - loss: 61.4346 - val_loss: 70.7138
Epoch 28/50
 - 0s - loss: 61.3475 - val_loss: 72.9382
Epoch 29/50
 - 0s - loss: 63.9922 - val_loss: 72.2265
Epoch 30/50
 - 0s - loss: 60.0230 - val_loss: 69.8599
Epoch 31/50
 - 0s - loss: 59.8262 - val_loss: 69.6800
Epoch 32/50
 - 0s - loss: 60.1375 - val_loss: 69.6162
Epoch 33/50
 - 0s - loss: 59.6167 - val_loss: 70.3507
Epoch 34/50
 - 0s - loss: 59.5139 - val_loss: 68.6021
Epoch 35/50
 - 0s - loss: 58.5208 - val_loss: 69.4341
Epoch 36/50
 - 0s - loss: 59.3230 - val_loss: 70.4003
Epoch 37/50
 - 0s - loss: 58.3219 - val_loss: 69.2802
Epoch 38/50
 - 0s - loss: 58.1296 - val_loss: 67.8231
Epoch 39/50
 - 0s - loss: 58.4748 - val_loss: 67.1188
Epoch 40/50
 - 0s - loss: 58.2305 - val_loss: 69.3459
Epoch 41/50
 - 0s - loss: 58.0800 - val_loss: 66.9076
Epoch 42/50
 - 0s - loss: 57.9641 - val_loss: 67.3192
Epoch 43/50
 - 0s - loss: 57.3636 - val_loss: 68.9581
Epoch 44/50
 - 0s - loss: 57.6314 - val_loss: 70.0047
Epoch 45/50
 - 0s - loss: 58.2509 - val_loss: 71.5737
Epoch 46/50
 - 0s - loss: 56.2492 - val_loss: 65.4471
Epoch 47/50
 - 0s - loss: 56.7025 - val_loss: 67.1763
Epoch 48/50
 - 0s - loss: 57.2932 - val_loss: 65.5452
Epoch 49/50
 - 0s - loss: 58.2497 - val_loss: 65.2276
Epoch 50/50
 - 0s - loss: 57.0789 - val_loss: 65.2836
Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 56.2797 - val_loss: 66.4087
Epoch 2/50
 - 0s - loss: 56.5837 - val_loss: 67.1519
Epoch 3/50
 - 0s - loss: 57.1274 - val_loss: 64.6104
Epoch 4/50
 - 0s - loss: 55.8155 - val_loss: 64.9150
Epoch 5/50
 - 0s - loss: 55.6598 - val_loss: 66.5873
Epoch 6/50
 - 0s - loss: 55.9883 - val_loss: 65.7817
Epoch 7/50
 - 0s - loss: 55.2977 - val_loss: 64.9420
Epoch 8/50
 - 0s - loss: 55.4405 - val_loss: 64.1528
Epoch 9/50
 - 0s - loss: 61.0310 - val_loss: 70.2760
Epoch 10/50
 - 0s - loss: 58.6620 - val_loss: 76.9481
Epoch 11/50
 - 0s - loss: 57.5332 - val_loss: 63.1226
Epoch 12/50
 - 0s - loss: 55.8447 - val_loss: 62.0127
Epoch 13/50
 - 0s - loss: 55.3705 - val_loss: 62.3344
Epoch 14/50
 - 0s - loss: 54.2612 - val_loss: 61.6045
Epoch 15/50
 - 0s - loss: 54.1451 - val_loss: 61.6821
Epoch 16/50
 - 0s - loss: 53.3448 - val_loss: 61.2187
Epoch 17/50
 - 0s - loss: 53.1498 - val_loss: 60.2339
Epoch 18/50
 - 0s - loss: 53.7828 - val_loss: 60.6727
Epoch 19/50
 - 0s - loss: 53.1031 - val_loss: 60.0550
Epoch 20/50
 - 0s - loss: 53.5531 - val_loss: 62.7334
Epoch 21/50
 - 0s - loss: 53.4179 - val_loss: 59.2014
Epoch 22/50
 - 0s - loss: 52.0369 - val_loss: 59.3930
Epoch 23/50
 - 0s - loss: 51.7097 - val_loss: 59.2533
Epoch 24/50
 - 0s - loss: 51.8268 - val_loss: 59.2024
Epoch 25/50
 - 0s - loss: 51.6381 - val_loss: 59.4800
Epoch 26/50
 - 0s - loss: 53.4015 - val_loss: 57.9573
Epoch 27/50
 - 0s - loss: 51.0671 - val_loss: 57.9739
Epoch 28/50
 - 0s - loss: 50.5565 - val_loss: 61.7178
Epoch 29/50
 - 0s - loss: 52.5836 - val_loss: 58.8114
Epoch 30/50
 - 0s - loss: 52.0125 - val_loss: 58.1708
Epoch 31/50
 - 0s - loss: 50.6375 - val_loss: 57.2724
Epoch 32/50
 - 0s - loss: 51.3014 - val_loss: 57.1561
Epoch 33/50
 - 0s - loss: 50.7106 - val_loss: 56.7250
Epoch 34/50
 - 0s - loss: 50.3181 - val_loss: 56.6530
Epoch 35/50
 - 0s - loss: 51.7538 - val_loss: 60.7634
Epoch 36/50
 - 0s - loss: 51.6346 - val_loss: 61.0656
Epoch 37/50
 - 0s - loss: 50.0077 - val_loss: 57.3006
Epoch 38/50
 - 0s - loss: 49.6582 - val_loss: 56.2886
Epoch 39/50
 - 0s - loss: 49.8250 - val_loss: 55.5477
Epoch 40/50
 - 0s - loss: 49.1923 - val_loss: 56.0415
Epoch 41/50
 - 0s - loss: 49.2732 - val_loss: 57.7241
Epoch 42/50
 - 0s - loss: 50.5421 - val_loss: 59.2910
Epoch 43/50
 - 0s - loss: 51.8123 - val_loss: 56.5756
Epoch 44/50
 - 0s - loss: 51.3347 - val_loss: 58.6299
Epoch 45/50
 - 0s - loss: 50.0463 - val_loss: 58.3939
Epoch 46/50
 - 0s - loss: 51.4947 - val_loss: 56.5202
Epoch 47/50
 - 0s - loss: 49.6332 - val_loss: 57.3740
Epoch 48/50
 - 0s - loss: 48.9768 - val_loss: 55.5920
Epoch 49/50
 - 0s - loss: 49.9309 - val_loss: 55.0498
Epoch 50/50
 - 0s - loss: 49.3601 - val_loss: 53.9622
Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 49.4408 - val_loss: 55.4264
Epoch 2/50
 - 0s - loss: 49.7447 - val_loss: 63.5232
Epoch 3/50
 - 0s - loss: 51.7234 - val_loss: 59.8316
Epoch 4/50
 - 0s - loss: 51.9285 - val_loss: 55.4345
Epoch 5/50
 - 0s - loss: 49.9199 - val_loss: 53.8001
Epoch 6/50
 - 0s - loss: 48.4892 - val_loss: 53.1876
Epoch 7/50
 - 0s - loss: 47.9254 - val_loss: 56.1980
Epoch 8/50
 - 0s - loss: 48.3402 - val_loss: 55.4321
Epoch 9/50
 - 0s - loss: 48.0928 - val_loss: 54.3786
Epoch 10/50
 - 0s - loss: 47.4037 - val_loss: 53.3657
Epoch 11/50
 - 0s - loss: 47.1813 - val_loss: 52.9569
Epoch 12/50
 - 0s - loss: 46.9614 - val_loss: 53.5356
Epoch 13/50
 - 0s - loss: 47.2948 - val_loss: 53.8251
Epoch 14/50
 - 0s - loss: 47.3540 - val_loss: 53.1441
Epoch 15/50
 - 0s - loss: 47.6217 - val_loss: 56.5083
Epoch 16/50
 - 0s - loss: 52.0947 - val_loss: 53.3284
Epoch 17/50
 - 0s - loss: 47.9174 - val_loss: 62.5724
Epoch 18/50
 - 0s - loss: 50.2480 - val_loss: 53.9328
Epoch 19/50
 - 0s - loss: 46.8156 - val_loss: 53.3420
Epoch 20/50
 - 0s - loss: 49.1598 - val_loss: 61.5189
Epoch 21/50
 - 0s - loss: 49.3405 - val_loss: 55.5880
Epoch 22/50
 - 0s - loss: 47.9926 - val_loss: 53.4529
Epoch 23/50
 - 0s - loss: 47.8734 - val_loss: 54.1093
Epoch 24/50
 - 0s - loss: 47.6969 - val_loss: 52.9444
Epoch 25/50
 - 0s - loss: 46.7474 - val_loss: 53.9510
Epoch 26/50
 - 0s - loss: 49.0810 - val_loss: 54.4006
Epoch 27/50
 - 0s - loss: 46.9780 - val_loss: 53.2367
Epoch 28/50
 - 0s - loss: 47.9243 - val_loss: 53.9429
Epoch 29/50
 - 0s - loss: 47.6913 - val_loss: 53.0430
Epoch 30/50
 - 0s - loss: 46.4554 - val_loss: 53.9137
Epoch 31/50
 - 0s - loss: 47.9285 - val_loss: 51.8379
Epoch 32/50
 - 0s - loss: 46.7976 - val_loss: 52.8143
Epoch 33/50
 - 0s - loss: 46.0178 - val_loss: 51.6739
Epoch 34/50
 - 0s - loss: 46.6270 - val_loss: 51.8540
Epoch 35/50
 - 0s - loss: 46.1633 - val_loss: 54.2855
Epoch 36/50
 - 0s - loss: 49.4226 - val_loss: 60.2794
Epoch 37/50
 - 0s - loss: 48.4367 - val_loss: 55.3972
Epoch 38/50
 - 0s - loss: 47.7155 - val_loss: 51.5760
Epoch 39/50
 - 0s - loss: 46.6881 - val_loss: 51.7848
Epoch 40/50
 - 0s - loss: 46.3297 - val_loss: 51.2450
Epoch 41/50
 - 0s - loss: 47.4928 - val_loss: 54.2275
Epoch 42/50
 - 0s - loss: 47.3233 - val_loss: 55.0639
Epoch 43/50
 - 0s - loss: 46.5887 - val_loss: 54.3944
Epoch 44/50
 - 0s - loss: 46.3544 - val_loss: 55.6055
Epoch 45/50
 - 0s - loss: 48.1417 - val_loss: 58.5215
Epoch 46/50
 - 0s - loss: 52.9993 - val_loss: 58.9902
Epoch 47/50
 - 0s - loss: 49.6291 - val_loss: 64.6945
Epoch 48/50
 - 0s - loss: 49.2192 - val_loss: 50.9033
Epoch 49/50
 - 0s - loss: 46.9250 - val_loss: 50.1502
Epoch 50/50
 - 0s - loss: 46.1296 - val_loss: 50.9561
Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 45.8110 - val_loss: 52.1076
Epoch 2/50
 - 0s - loss: 46.4140 - val_loss: 52.2074
Epoch 3/50
 - 0s - loss: 47.4825 - val_loss: 50.9642
Epoch 4/50
 - 0s - loss: 47.1196 - val_loss: 50.3190
Epoch 5/50
 - 0s - loss: 45.9374 - val_loss: 51.7266
Epoch 6/50
 - 0s - loss: 45.6246 - val_loss: 50.7041
Epoch 7/50
 - 0s - loss: 46.8285 - val_loss: 50.5843
Epoch 8/50
 - 0s - loss: 47.1900 - val_loss: 51.6033
Epoch 9/50
 - 0s - loss: 46.0676 - val_loss: 52.8546
Epoch 10/50
 - 0s - loss: 46.3704 - val_loss: 50.2841
Epoch 11/50
 - 0s - loss: 46.0207 - val_loss: 52.4033
Epoch 12/50
 - 0s - loss: 46.2800 - val_loss: 50.4664
Epoch 13/50
 - 0s - loss: 46.8684 - val_loss: 51.8115
Epoch 14/50
 - 0s - loss: 47.9057 - val_loss: 53.8626
Epoch 15/50
 - 0s - loss: 50.4825 - val_loss: 51.3740
Epoch 16/50
 - 0s - loss: 48.2834 - val_loss: 49.8425
Epoch 17/50
 - 0s - loss: 46.8036 - val_loss: 49.9543
Epoch 18/50
 - 0s - loss: 45.8247 - val_loss: 50.0499
Epoch 19/50
 - 0s - loss: 45.5971 - val_loss: 50.2208
Epoch 20/50
 - 0s - loss: 45.4607 - val_loss: 50.3548
Epoch 21/50
 - 0s - loss: 46.5687 - val_loss: 57.3984
Epoch 22/50
 - 0s - loss: 46.8149 - val_loss: 49.8500
Epoch 23/50
 - 0s - loss: 47.3635 - val_loss: 54.8783
Epoch 24/50
 - 0s - loss: 45.7385 - val_loss: 50.0489
Epoch 25/50
 - 0s - loss: 45.3131 - val_loss: 50.8368
Epoch 26/50
 - 0s - loss: 46.0490 - val_loss: 49.5002
Epoch 27/50
 - 0s - loss: 46.0114 - val_loss: 50.1352
Epoch 28/50
 - 0s - loss: 45.8181 - val_loss: 50.1431
Epoch 29/50
 - 0s - loss: 45.6636 - val_loss: 49.9214
Epoch 30/50
 - 0s - loss: 45.6888 - val_loss: 50.7404
Epoch 31/50
 - 0s - loss: 45.1597 - val_loss: 49.5803
Epoch 32/50
 - 0s - loss: 44.9056 - val_loss: 49.9103
Epoch 33/50
 - 0s - loss: 45.0281 - val_loss: 49.8257
Epoch 34/50
 - 0s - loss: 47.6679 - val_loss: 51.8161
Epoch 35/50
 - 0s - loss: 46.7145 - val_loss: 51.1752
Epoch 36/50
 - 0s - loss: 45.5268 - val_loss: 49.2734
Epoch 37/50
 - 0s - loss: 46.2022 - val_loss: 52.6956
Epoch 38/50
 - 0s - loss: 46.5764 - val_loss: 53.2599
Epoch 39/50
 - 0s - loss: 44.9440 - val_loss: 51.2695
Epoch 40/50
 - 0s - loss: 45.1276 - val_loss: 50.5782
Epoch 41/50
 - 0s - loss: 45.3303 - val_loss: 50.5808
Epoch 42/50
 - 0s - loss: 45.4191 - val_loss: 49.9189
Epoch 43/50
 - 0s - loss: 45.6914 - val_loss: 48.8545
Epoch 44/50
 - 0s - loss: 45.7810 - val_loss: 50.7860
Epoch 45/50
 - 0s - loss: 46.3993 - val_loss: 53.4070
Epoch 46/50
 - 0s - loss: 46.7385 - val_loss: 51.4271
Epoch 47/50
 - 0s - loss: 45.3691 - val_loss: 49.6216
Epoch 48/50
 - 0s - loss: 45.2793 - val_loss: 51.3507
Epoch 49/50
 - 0s - loss: 47.3653 - val_loss: 55.5068
Epoch 50/50
 - 0s - loss: 46.5308 - val_loss: 50.2724
Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 48.0508 - val_loss: 50.7216
Epoch 2/50
 - 0s - loss: 46.0763 - val_loss: 50.4005
Epoch 3/50
 - 0s - loss: 44.5496 - val_loss: 50.2111
Epoch 4/50
 - 0s - loss: 45.6044 - val_loss: 50.8515
Epoch 5/50
 - 0s - loss: 45.0493 - val_loss: 49.6999
Epoch 6/50
 - 0s - loss: 46.3579 - val_loss: 49.7069
Epoch 7/50
 - 0s - loss: 46.9066 - val_loss: 49.8878
Epoch 8/50
 - 0s - loss: 46.1273 - val_loss: 49.5825
Epoch 9/50
 - 0s - loss: 44.6649 - val_loss: 49.9410
Epoch 10/50
 - 0s - loss: 45.8232 - val_loss: 49.2345
Epoch 11/50
 - 0s - loss: 45.9295 - val_loss: 49.4894
Epoch 12/50
 - 0s - loss: 45.0315 - val_loss: 51.1326
Epoch 13/50

In [36]:
print(" ")
print("total mean squared error: ", np.mean(mse_total), "\n")
print("standard deviation of total mean squared error: ", np.std(mse_total))

total mean squared error:  59.48303553460469

standard deviation of total mean squared error:  14.692968262327428